package entity.enumertion;

public enum Grade {
    ASSOCIATE,
    DISCONTINUOUS_BACHELOR,
    CONTINUOUS_BACHELOR,
    DISCONTINUOUS_MASTER,
    CONTINUOUS_MASTER,
    DISCONTINUOUS_PROFESSIONAL_DOCTORAL,
    CONTINUOUS_PROFESSIONAL_DOCTORAL,
    EXPERT_DOCTORAL
}