package entity.enumertion;

public enum Grade {
    ASSOCIATE,
    DISCONTINUOUSBACHELOR,
    CONTINUOUSBACHELOR,
    DISCONTINUOUSMASTER,
    CONTINUOUSMASTER,
    DISCONTINUOUSPROFESSIONALDOCTORAL,
    CONTINUOUSPROFESSIONALDOCTORAL,
    EXPERTDOCTORAL
}